// Civilization/era icons shown on locked + unlocked trunk nodes on the Learn screen.
// Generated by scripts/generate-civ-images.js.
export const civImages: Record<string, any> = {
  'ancient-beginnings': require('@/assets/images/civs/ancient-beginnings.png'),
  'medieval-clashes': require('@/assets/images/civs/medieval-clashes.png'),
  'napoleonic-era': require('@/assets/images/civs/napoleonic-era.png'),
  'great-war': require('@/assets/images/civs/great-war.png'),
  'world-war-2': require('@/assets/images/civs/world-war-2.png'),
  'ancient-asia': require('@/assets/images/civs/ancient-asia.png'),
  'mongol-conquests': require('@/assets/images/civs/mongol-conquests.png'),
  'samurai-era': require('@/assets/images/civs/samurai-era.png'),
  'pacific-theater': require('@/assets/images/civs/pacific-theater.png'),
  'ancient-africa': require('@/assets/images/civs/ancient-africa.png'),
  'colonial-resistance': require('@/assets/images/civs/colonial-resistance.png'),
  'north-africa-ww2': require('@/assets/images/civs/north-africa-ww2.png'),
  'american-revolution': require('@/assets/images/civs/american-revolution.png'),
  'american-civil-war': require('@/assets/images/civs/american-civil-war.png'),
  'latin-american-wars': require('@/assets/images/civs/latin-american-wars.png'),
  'roman-empire': require('@/assets/images/civs/roman-empire.png'),
  'crusades': require('@/assets/images/civs/crusades.png'),
  'naval-supremacy': require('@/assets/images/civs/naval-supremacy.png'),
  'indian-subcontinent': require('@/assets/images/civs/indian-subcontinent.png'),
  'korean-glory': require('@/assets/images/civs/korean-glory.png'),
  'african-resistance': require('@/assets/images/civs/african-resistance.png'),
  'conquest-of-americas': require('@/assets/images/civs/conquest-of-americas.png'),
  'modern-americas': require('@/assets/images/civs/modern-americas.png'),
};

export function getCivImage(unitId: string): any | undefined {
  return civImages[unitId];
}
