/**
 * Regenerates mocks/images.ts from the files present in assets/images.
 * Run: npx tsx scripts/art/writeImageIndex.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const root = path.join(__dirname, '..', '..');
const list = (dir: string, ext: string) =>
  fs.existsSync(path.join(root, dir))
    ? fs
        .readdirSync(path.join(root, dir))
        .filter((f) => f.endsWith(ext))
        .map((f) => f.replace(ext, ''))
        .sort()
    : [];

const battles = list('assets/images/battles', '.jpg');
const emblems = list('assets/images/emblems', '.jpg');
const mascots = list('assets/images/mascots', '.jpg');

const entries = (ids: string[], dir: string) =>
  ids.map((id) => `  '${id}': require('@/assets/images/${dir}/${id}.jpg'),`).join('\n');

const out = `// Generated by scripts/art/writeImageIndex.ts — do not edit by hand.
// Painted artwork generated with Higgsfield (z_image), downscaled for the app bundle.
/* eslint-disable @typescript-eslint/no-require-imports */
import type { ImageSourcePropType } from 'react-native';

export const battleImages: Record<string, ImageSourcePropType> = {
${entries(battles, 'battles')}
};

export const emblemImages: Record<string, ImageSourcePropType> = {
${entries(emblems, 'emblems')}
};

export const mascotImages: Record<string, ImageSourcePropType> = {
${entries(mascots, 'mascots')}
};

export const artImages = {
  onboardingHero: require('@/assets/images/art/onboarding-hero.jpg') as ImageSourcePropType,
};

export const getBattleImage = (battleId: string): ImageSourcePropType | undefined => battleImages[battleId];
export const getEmblemImage = (unitId: string): ImageSourcePropType | undefined => emblemImages[unitId];
export const getMascotImage = (mascotId: string): ImageSourcePropType | undefined => mascotImages[mascotId];
`;

fs.writeFileSync(path.join(root, 'mocks', 'images.ts'), out);
console.log(`images.ts: ${battles.length} battles, ${emblems.length} emblems, ${mascots.length} mascots`);
