/**
 * Builds mocks/worldLand.ts from Natural Earth 1:110m land polygons.
 *
 * Usage:
 *   curl -L -o /tmp/ne_110m_land.geojson \
 *     https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_110m_land.geojson
 *   node scripts/geo/buildWorldLand.mjs /tmp/ne_110m_land.geojson
 *
 * Output is a list of rings, each a flat [lng, lat, lng, lat, ...] array rounded to
 * 0.1 degree, which is well under a pixel at the zoom levels MapTap uses.
 * Natural Earth data is public domain.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2];
if (!src) {
  console.error('usage: node scripts/geo/buildWorldLand.mjs <ne_110m_land.geojson>');
  process.exit(1);
}
const geo = JSON.parse(readFileSync(src, 'utf8'));
const rings = [];
for (const f of geo.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    for (const ring of poly) {
      const flat = [];
      let px = null;
      let py = null;
      for (const [lng, lat] of ring) {
        const x = Math.round(lng * 10) / 10;
        const y = Math.round(lat * 10) / 10;
        if (x === px && y === py) continue;
        flat.push(x, y);
        px = x;
        py = y;
      }
      if (flat.length >= 8) rings.push(flat);
    }
  }
}
const body = rings.map((r) => `  [${r.join(',')}],`).join('\n');
const out = `// Generated by scripts/geo/buildWorldLand.mjs from Natural Earth 1:110m land (public domain).
// Each ring is a flat [lng, lat, lng, lat, ...] list. Do not edit by hand.

export const WORLD_LAND: number[][] = [
${body}
];
`;
writeFileSync(new URL('../../mocks/worldLand.ts', import.meta.url), out);
console.log(`${rings.length} rings, ${rings.reduce((n, r) => n + r.length / 2, 0)} points, ${out.length} bytes`);
